### ISSUE TITLE
get_dataset for GP Practice Contact Details and List Sizes dataset fails

### ISSUE THREAD

**Issue by datagestive** [Public-Health-Scotland/phsopendata#9]
Using get_dataset on the "gp-practice-contact-details-and-list-sizes" dataset returns an error:
```
Error: Can't combine `..1$PracticeListSize` <integer> and `..21$PracticeListSize` <character>.
```
So this particular dataset can't be downloaded in bulk with this package.

**Comment by Moohan** [comment]
Same as [I mentioned](https://github.com/Public-Health-Scotland/phsopendata/issues/8#issuecomment-1117265704) in #6

**Comment by csillasch** [comment]
@datagestive This is now resolved.
